# Generated by Django 4.2.4 on 2023-08-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("image_link", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("code", models.IntegerField()),
                ("img_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Stores",
                "indexes": [
                    models.Index(fields=["code"], name="cornershopa_code_565576_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("package", models.CharField(blank=True, max_length=256, null=True)),
                ("image_link", models.URLField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cornershopapp.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Price_product_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("consultation_date", models.DateTimeField(auto_now_add=True)),
                ("consultation_day", models.IntegerField()),
                ("consultation_month", models.IntegerField()),
                ("consultation_year", models.IntegerField()),
                ("consultation_weekNumber", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cornershopapp.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price_product_history",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cornershopapp.store"
            ),
        ),
        migrations.CreateModel(
            name="Aisle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("cod", models.CharField(max_length=256)),
                ("image_link", models.URLField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cornershopapp.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aisles",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="cornershopa_name_248eb5_idx"),
        ),
        migrations.AddIndex(
            model_name="price_product_history",
            index=models.Index(
                fields=["product"], name="cornershopa_product_a6fddc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["cod"], name="cornershopa_cod_1f3bd2_idx"),
        ),
        migrations.AddIndex(
            model_name="aisle",
            index=models.Index(fields=["cod"], name="cornershopa_cod_8e41e3_idx"),
        ),
    ]
